### ISSUE TITLE
I can't use the function twice

### ISSUE THREAD

**Issue by pisteuralpin** [brandonmcconnell/scss-typewriter#17]
I'm using the function like this but for both the displayed text is "••••••••••••••••••••"

```scss
.windows-viewport.loaded .viewport-locked .password {
	@include typed(
		"••••••••••••••••••••",
		null,
		(delay: 2, caret-width: 2px, caret-space: 2px, iterations: 0)
	);
}

#about-presentation {
	@include typed(
		"text",
		(type: .1), (caret-width: 2px, caret-space: 2px)
	);
}
```

**Comment by brandonmcconnell** [comment]
@pisteuralpin Could you create a reproducible example of this online (maybe codepen.io) where I can troubleshoot the issue?

**Comment by HansKing98** [comment]
You need to use a different 'name' ,
like this,
```css
.my-typed {
	padding: 0 0 0 3px;
    background-color:blue;

	&::before { font-weight: 400; }
	@include typed(
            "Happy",
            "Angry"
        (   type: .07,pause-typed: 2,delete: .08,pause-deleted: 1),
        (   
            name: "my-typewriter-9999", 
            caret: true,caret-speed: .75,caret-width: 2px,caret-color: currentColor,caret-space: .1ch,
            delay: 1,iterations: infinite,
        )

	);
}
.my-typed2 {
	padding: 0 0 0 3px;
    background-color:blue;

	&::before { font-weight: 400; }
	@include typed(
            "Happy2",
            "Angry2"
        (   type: .07,pause-typed: 2,delete: .08,pause-deleted: 1),
        (   
            name: "my-typewriter-9999-2", 
            caret: true,caret-speed: .75,caret-width: 2px,caret-color: currentColor,caret-space: .1ch,
            delay: 1,iterations: infinite,
        )

	);
}
```
