### ISSUE TITLE
use var(--text) for text

### ISSUE THREAD

**Issue by yacosta738** [brandonmcconnell/scss-typewriter#3]
Hi, great work. I try to use variables in my scss files for i18n purposes, but when I use var(--variable) print "var(--variable)".

![image](https://user-images.githubusercontent.com/33158051/186787070-ebd9070c-ccde-495f-a575-e8fa54491634.png)

![image](https://user-images.githubusercontent.com/33158051/186787146-ddf4e9ff-5a9d-4902-be5a-60c90a2a3500.png)

Is it possible to use variables for text?

**Comment by brandonmcconnell** [comment]
@yacosta738 Unfortunately, it's not possible to use CSS custom properties (`var(--var-name)` variables) within Sass/SCSS, as those are processed at runtime. That's a Sass thing, not a Typed.css thing 🤷🏻‍♂️

However, the general workaround for that is to declare the variable twice, like this, so the CSS custom property uses the value of the SCSS variable, so you only have to maintain its value in one place:

```scss
$myText: "some text here to be used within a typewriter";
:root {
  --myText: #{$myText};
}
selector {
  @include typed(
    $myText,
    1.5,
    (
      caret-width: 2px,
      caret-space: 2px
    )
  )
}
```

Hope this works for you! I'm happy to answer any other questions you have about this.

More on the difference between CSS custom properties and Sass/SCSS variables here:
https://sass-lang.com/documentation/breaking-changes/css-vars
